### PR TITLE
created a bangazonreports app, templates, & views, created a usersfav…

### LINKED ISSUE #22: REPORT: Completed orders
As a business analyst, I would like to see an HTML report showing all orders that have been paid for.

* Order Id
* Customer name
* Total paid for the order
* Payment type

### PR DESCRIPTION
**Pull request by MarkyAaronYoung**
…oritesellers list WIP

Description of PR that completes issue here...

## Changes

- added a bangazon reports app
- created a template for favorited sellers (WIP)
- created a usersfavsellers module and function for generating a users favorite sellers report

## Requests / Responses

If this PR contains code that defines a new request/response, or changes an existing one, please put the JSON representations here.

**Request**

GET `/usersfavorites` 

```json
{
    "customer_id": 6,
    "seller_id": 5,
    "full_name": "Brenda Long",
}
```

No response yet WIP
```

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database


## Related Issues

- Fixes #85
- Fixes #22

### CODE REVIEW

**Comment by mitchellblom** [comment]
Are the related tickets ready to test? All of your tickets are still in the backlog.

**Comment by mitchellblom** [comment]
There are references to WIP. Can you please only PR what is ready for review?

**Comment by MarkyAaronYoung** [comment]
> Are the related tickets ready to test? All of your tickets are still in the backlog.

I just moved Favorited Sellers by Customer over to in-progress.  This is going to take me a bit. I'll wait to push up code when it's working.

**Comment by mitchellblom** [comment]
Thanks. In general smaller PRs are better. Bite sized code is easier to review.

**Comment by mitchellblom** [comment]
Please close this PR if it is no longer needed.

**Comment by MarkyAaronYoung** [comment]
PR closed.

**Pull request closed without merging**
